// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://akspwnwfpbgaxqdudkgi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFrc3B3bndmcGJnYXhxZHVka2dpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ5Mjk2MjAsImV4cCI6MjA3MDUwNTYyMH0.959-RLRi2TGAgAdaQyXyY_qqEojW2Tr3_09db9IK95w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});